WIP: fix the compilation issue of the unittest
```
guc_gp_test.o: In function `write_gp_replication_conf_file':
/tmp/build/f8c7ee08/gpdb_src/src/backend/utils/misc/test/../guc_gp.c:6415: undefined reference to `escape_single_quotes_ascii'
```

The function is in libpgport, so we added it back to pass the
compilation.

We only see this issue on CI, not locally.

Signed-off-by: Abhijit Subramanya <asubramanya@pivotal.io>